Repository DEVMeshLabs/rentskins_frontend, pull requests merged in 2023-07, with the labels that each got.

#4 [ Tiago Braga ] Tweaks - Correção de Features/Erros
  src/app/home/page.tsx
  src/app/perfil/[steamid]/page.tsx
  src/app/perfil/page.tsx
  src/app/usuario/configuracoes/page.tsx
  src/components/Layout/LayoutRoot.tsx
  src/tools/authentication.tool.ts
  src/tools/localstorage.tool.ts
Labels: Prioridade: Baixa, Refatoração

#6 [ Gabriel Almeida ] Notificações - Conxeção de notificações com o back
  src/app/usuario/notificacoes/page.tsx
  src/components/Layout/Header/LayoutHeaderTop.tsx
  src/components/Modal/ModalNotification/ModalNotificationFilter.tsx
  src/components/Others/NotificationCard/NotificationImage.tsx
  src/components/Pages/PageNotification/PageNotificationHistoric.tsx
  src/services/interfaces/notification.interface.ts
  src/services/notifications.service.ts
  src/stores/filters.store.ts
  src/stores/interfaces/filters.interface.ts
  src/utils/notification.ts
Labels: Code Review

#7 [ Gabriel Almeida ] - Lazy Loading - Implementando dynamic #167
  src/app/carrinho/page.tsx
  src/app/categorias/[skinName]/page.tsx
  src/app/detalhes/[id]/page.tsx
  src/app/home/page.tsx
  src/app/inventario/page.tsx
  src/app/loja/page.tsx
  src/app/usuario/notificacoes/page.tsx
  src/components/Others/Skins/AllSkeletonSkins/index.tsx
  src/components/Others/Skins/AllSkins/index.tsx
  src/components/Others/Skins/SkeletonCardSkin/index.tsx
  src/components/Others/SkinsSemelhantes/index.tsx
  src/components/Pages/PageInventory/PageInventoryFilters.tsx
  src/components/Pages/PageInventory/PageInventoryMiddle.tsx
  src/components/Pages/PageInventory/PageInventorySummary.tsx
  src/components/Pages/PageNotification/PageNotificationHistoric.tsx
  src/components/Pages/PageNotification/PageNotificationTransaction.tsx
  src/components/Pages/PageSummary/PageSummaryCart.tsx
  src/components/Skins/AllSkeletonSkins/index.tsx
Labels: Melhoria, Adição/Feature, Code Review, Refatoração

#8 [ Gabriel Almeida ] Inteventário - adicionando parte da conexão com o back e refatorando lógica
  package.json
  src/app/inventario/page.tsx
  src/components/Modal/ModalConnectInventory/ModalConnectInventoryForm.tsx
  src/components/Modal/ModalSkinShowcase/ModalSkinShowcaseInfo.tsx
  src/components/Modal/ModalSkinShowcase/ModalSkinShowcaseMain.tsx
  src/components/Modal/ModalSkinShowcase/info.schema.ts
  src/components/Others/CardSkin/CardSkinInventory.tsx
  src/components/Others/NotificationCard/NotificationImage.tsx
  src/components/Others/OtherCard/OtherCard.tsx
  src/components/Pages/PageInventory/PageInventoryFilters.tsx
  src/components/Pages/PageInventory/PageInventorySummary.tsx
  src/interfaces/ISkins.ts
  src/services/config.service.ts
  src/services/interfaces/inventoryy.interface.ts
  src/services/skin.service.ts
  src/stores/interfaces/skins.interface.ts
  src/stores/skins.store.ts
  src/utils/bitli.ts
  yarn.lock
Labels: Melhoria, Code Review, Refatoração
