Repository DEVMeshLabs/rentskins_frontend, pull requests merged in 2023-08, with the labels that each got.

#12 [ Gabriel Almeida ] Perfil - Conexão com o back end
  .env
  next.config.js
  package.json
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/pagamento/saque/page.tsx
  src/app/perfil/[steamid]/page.tsx
  src/app/perfil/[userSteamId]/page.tsx
  src/app/perfil/page.tsx
  src/components/Common/CommonSearchFeedback.tsx
  src/components/Common/index.tsx
  src/components/Forms/Input/Radio/FormInputRadioChoice.tsx
  src/components/Modal/ModalConnectInventory/ModalConnectInventoryForm.copy.tsx
  src/components/Modal/ModalNotification/ModalNotificationFilter.tsx
  src/components/Others/CartSkinCard/index.tsx
  src/components/Others/ProfileInfo/index.tsx
  src/components/Others/ProfilePerson/index.tsx
  src/components/SkeletonCardSkin/index.tsx
  src/components/Skins/AllSkeletonSkins/index.tsx
  src/services/interfaces/user.interface.ts
  src/services/skin.service.ts
  src/services/user.service.ts
  yarn.lock
Labels: Merge, Adição/Feature, Code Review

#24 [ Gabriel Almeida ] Carrinnho - Conexão com o back
  src/app/detalhes/[id]/page.tsx
  src/app/layout.tsx
  src/components/Others/CartSkinCard/index.tsx
  src/components/Others/Skins/AllSkinsCart/index.tsx
  src/components/Pages/PageDetails/PageDetailsSkin.tsx
  src/components/Pages/PageHome/PageHomeSkins.tsx
  src/components/Pages/PageStore/PageStoreSkins.tsx
  src/interfaces/ISkins.ts
  src/middleware.ts
  src/services/cart.service.ts
  src/services/interfaces/cart.interface.ts
  src/services/interfaces/user.interface.ts
  src/services/skin.service.ts
  src/stores/cart.store.ts
  src/stores/interfaces/cart.interface.ts
Labels: Adição/Feature, Code Review

#25 [ Tiago Braga ] Tweaks - Alterando Nome das Facas (#212)
  src/components/Layout/Header/LayoutHeaderBottom.tsx
Labels: Code Review, Refatoração

#26 [ Tiago Braga ] Tweaks - Conferindo Paginação nas Páginas (#211)
  src/app/detalhes/[id]/page.tsx
  src/app/home/page.tsx
  src/app/loja/page.tsx
  src/app/perfil/[userSteamId]/page.tsx
  src/app/perfil/page.tsx
  src/components/Common/CommonSearchFeedback.tsx
  src/components/Layout/Header/LayoutHeaderTop.tsx
  src/components/Modal/ModalFilters/ModalFiltersStandard.tsx
  src/components/Modal/ModalFilters/ModalFiltersWear.tsx
  src/components/Others/OtherCard/OtherCard.tsx
  src/components/Others/PersonProfile/index.tsx
  src/components/Others/ProfileInfo/index.tsx
  src/components/Others/Skins/AllSkeletonSkins/index.tsx
  src/components/Others/Skins/AllSkins/index.tsx
  src/components/Others/Skins/RentedSkins/index.tsx
  src/components/Others/SkinsSemelhantes/index.tsx
  src/components/Pages/PageDetails/PageDetailsCard.tsx
  src/components/Pages/PageHome/PageHomeSkins.tsx
  src/components/Pages/PageProfile/PageProfileSelf.tsx
  src/components/Pages/PageProfile/PageProfileUser.tsx
  src/components/Pages/PageStore/PageStoreSkins.tsx
  src/interfaces/ISkins.ts
  src/services/notifications.service.ts
  src/services/skin.service.ts
  src/services/user.service.ts
  tailwind.config.js
Labels: Melhoria, Code Review

#27 [ Tiago Braga ] Tweaks - Adicionando o campo 'CPF' nas 'Configurações'
  src/components/Forms/Input/FormInputCPF.tsx
  src/components/Pages/PageSettings/PageSettingsInformation.tsx
  src/components/Pages/PageSettings/schemas/information-cpf.contact.schema.ts
  src/interfaces/IConfig.ts
  src/services/config.service.ts
Labels: Adição/Feature, Code Review

#23 [ Gabriel Almeida ] Loja - Conexão com o back end, lógica de filtros e refatoração de modais
  src/app/detalhes/[id]/page.tsx
  src/components/Dropdown/ModalFilterCategories/FilterCategory/index.tsx
  src/components/Dropdown/ModalFilterCategories/FilterPrice/InputValue.tsx
  src/components/Dropdown/ModalFilterCategories/FilterPrice/index.tsx
  src/components/Dropdown/ModalFilterCategories/FilterStandard/StandardCheckboxItem.tsx
  src/components/Dropdown/ModalFilterCategories/FilterStandard/index.tsx
  src/components/Forms/Input/FormInputCheckbox.tsx
  src/components/Forms/Input/FormInputCurrency.tsx
  src/components/InputCheckboxFilter/index.tsx
  src/components/Modal/ModalFilters/ModalFiltersCategory.tsx
  src/components/Modal/ModalFilters/ModalFiltersMain.tsx
  src/components/Modal/ModalFilters/ModalFiltersPrice.tsx
  src/components/Modal/ModalFilters/ModalFiltersStandard.tsx
  src/components/Modal/ModalFilters/ModalFiltersWear.tsx
  src/components/Modal/ModalFilters/price.schema.ts
  src/components/Modal/ModalFilters/schemas/Wear.schhema.ts
  src/components/Modal/ModalFilters/schemas/category.schema.ts
  src/components/Modal/ModalFilters/schemas/price.schema.ts
  src/components/Others/SkinFilters/index.tsx
  src/components/Others/Skins/AllSkins/index.tsx
  src/components/Pages/PageDetails/PageDetailsPerfil.tsx
  src/components/Pages/PageStore/PageStoreSkins.tsx
  src/stores/filters.store.ts
  src/stores/interfaces/filters.interface.ts
Labels: Melhoria, Adição/Feature, Code Review

#28 [ Gabriel Almeida ] Tweaks - Redirecionamento ao clicar no perfil && 'Total de Trocas' para 'Total de Transações'
  src/app/detalhes/[id]/page.tsx
  src/app/perfil/[userSteamId]/page.tsx
  src/components/Others/PersonProfile/index.tsx
  src/components/Pages/PageDetails/PageDetailsPerfil.tsx
Labels: Adição/Feature, Code Review

#31 [ Gabriel Almeida ] Carrinho - Adicionando dinamismo ao sumario e retirando a taxa de compra.
  src/components/Common/CommonSearchFeedback.tsx
  src/components/Common/CommonTitle.tsx
  src/components/Others/CartSkinCard/index.tsx
  src/components/Others/Skins/AllSkinsCart/index.tsx
  src/components/Others/SummaryItem/index.tsx
  src/components/Pages/PageDetails/PageDetailsPerfil.tsx
  src/components/Pages/PageSummary/PageSummaryCart.tsx
  src/components/Pages/PageSummary/PageSummaryInfo.tsx
Labels: Adição/Feature, Code Review

#32 [ Tiago Braga ] Tweaks - Refatorando o Modal de Configurações (#238/235)
  src/app/inventario/page.tsx
  src/app/termos-de-uso/page.tsx
  src/components/Layout/Header/LayoutHeaderTop.tsx
  src/components/Modal/ModalConnectInventory/ModalConnectInventoryForm.tsx
  src/components/Modal/ModalConnectInventory/ModalConnectInventoryMain.tsx
  src/components/Modal/ModalConnectInventory/form.schema.ts
  src/components/Pages/PageInventory/PageInventoryMiddle.tsx
  src/components/Pages/PageSettings/PageSettingsSecurity.tsx
  src/components/Pages/PageUser/PageUserConfigurations.tsx
Labels: Code Review, Refatoração
