Repository DEVMeshLabs/rentskins_frontend, pull requests merged in 2023-09, with the labels that each got.

#37 [ Tiago Braga ] Tweaks - Lógica de Verificação do Item em Detalhes (#237)
  src/app/detalhes/[id]/page.tsx
  src/app/home/page.tsx
  src/components/Common/CommonSteamButton.tsx
  src/components/Forms/Input/Radio/FormInputRadioDefault.tsx
  src/components/Layout/Header/LayoutHeaderTop.tsx
  src/components/Modal/ModalConnectInventory/ModalConnectInventoryForm.tsx
  src/components/Modal/ModalConnectInventory/ModalConnectInventoryMain.tsx
  src/components/Others/CardSkin/CardSkinInventory.tsx
  src/components/Others/PersonProfile/index.tsx
  src/components/Others/SkinsSemelhantes/index.tsx
  src/components/Pages/PageDetails/PageDetailsCard.tsx
  src/components/Pages/PageDetails/PageDetailsMain.tsx
  src/components/Pages/PageDetails/PageDetailsPerfil.tsx
  src/components/Pages/PageDetails/PageDetailsSkin.tsx
  src/components/Pages/PageDetails/PageDetailsVendas.tsx
  src/components/Pages/PageDetails/schemas/form.schema.ts
  src/components/Pages/PageHome/PageHomeSkins.tsx
  src/components/Pages/PageInventory/PageInventoryMiddle.tsx
  src/components/Pages/PageProfile/PageProfileSelf.tsx
  src/components/Pages/PageProfile/PageProfileUser.tsx
  src/components/Pages/PageStore/PageStoreSkins.tsx
  src/interfaces/IConfig.ts
  src/interfaces/ISkins.ts
  src/services/interfaces/user.interface.ts
  src/services/skin.service.ts
  src/services/user.service.ts
  src/tools/toast.tool.ts
Labels: Adição/Feature

#38 [ Gabriel Almeida ] Tweaks - Adicionando color ao nome da skin e novos checkbox para anunciar uma skin
  src/components/Layout/Header/LayoutHeaderTop.tsx
  src/components/Modal/ModalSkinShowcase/ModalSkinShowcaseInfo.tsx
  src/components/Modal/ModalSkinShowcase/info.schema.ts
  src/components/Others/OtherCard/OtherCard.tsx
Labels: Adição/Feature, Code Review

#36 [ Gabriel Almeida ] Inventário - corrigindo erro NaN no sumario
  src/app/layout.tsx
  src/components/Layout/Header/LayoutHeaderTop.tsx
  src/components/Modal/ModalConnectInventory/ModalConnectInventoryForm.tsx
  src/components/Pages/PageDetails/PageDetailsSkin.tsx
  src/components/Pages/PageInventory/PageInventorySummary.tsx
Labels: Code Review

#39 [ Tiago Braga ] Tweaks - Alterando Filtros da Loja (#253)
  src/components/Modal/ModalFilters/ModalFiltersMain.tsx
  src/components/Modal/ModalFilters/ModalFiltersStandard.tsx
  src/components/Modal/ModalFilters/ModalFiltersWear.tsx
  src/components/Others/SkinFilters/index.tsx
  src/components/Pages/PageStore/PageStoreSkins.tsx
  src/stores/interfaces/filters.interface.ts
Labels: Code Review, Refatoração, Prioridade: Baixa

#41 [ Gabriel Almeida ] Tweaks - Implementando feedback no card da skin deletada.
  src/components/Others/OtherCard/OtherCard.tsx
  src/components/Others/Skins/AllSkins/index.tsx
  src/components/Others/SkinsSemelhantes/index.tsx
  src/components/Pages/PageDetails/PageDetailsCard.tsx
  src/components/Pages/PageDetails/PageDetailsMain.tsx
  src/components/Pages/PageProfile/PageProfileSelf.tsx
  src/interfaces/ISkins.ts
Labels: Adição/Feature, Code Review

#40 [ Gabriel Almeida ] Correções Menores
  src/components/Modal/ModalSkinShowcase/ModalSkinShowcaseInfo.tsx
  src/components/Others/CardSkin/CardSkinInventory.tsx
  src/components/Others/OtherCard/OtherCard.tsx
  src/components/Pages/PageDetails/PageDetailsSkin.tsx
Labels: Melhoria, Adição/Feature

#42 [ Gabriel Almeida ] Tweaks - Lógica no carrinho para não renderizar skins excluídas.
  src/components/Others/Skins/AllSkinsCart/index.tsx
  src/components/Others/SummaryItem/index.tsx
  src/components/Pages/PageDetails/PageDetailsCard.tsx
Labels: Adição/Feature, Code Review

#45 [ Gabriel Almeida ] Tweaks - Usuário não compra, aluga ou adiciona ao carrinho a própria skin.
  src/components/Pages/PageDetails/PageDetailsMain.tsx
  src/components/Pages/PageDetails/PageDetailsSkin.tsx
  src/components/Pages/PageInventory/PageInventorySummary.tsx
Labels: Code Review

#46 [ Tiago Braga ] Tweaks - Corrigindo o Carrinho (#255)
  src/components/Layout/Header/LayoutHeaderTop.tsx
  src/components/Others/Skins/AllSkinsCart/index.tsx
  src/components/Pages/PageDetails/PageDetailsSkin.tsx
  src/components/Pages/PageInventory/PageInventoryMiddle.tsx
  src/services/notifications.service.ts
Labels: Prioridade: Média, Refatoração

#51 [ Gabriel Almeida ] Tweaks - Toast aparece caso o login do usuário de erro (#262-265)
  src/app/layout.tsx
  src/components/Layout/Header/LayoutHeaderTop.tsx
  src/components/Layout/LayoutRoot.tsx
  src/components/Pages/PageUser/PageUserNotification/PageUserNotifications.tsx
  src/services/notifications.service.ts
  yarn.lock
Labels: Adição/Feature, Code Review

#52 [ Gabriel Almeida ] Tweaks - Adicionando glow no StatTrack do card das Skins do inventário (#264)
  src/components/Others/CardSkin/CardSkinContent.tsx
Labels: Melhoria, Code Review

#54 Tweaks/task#268
  src/components/Layout/Header/LayoutHeaderTop.tsx
  src/components/Modal/ModalSkinShowcase/ModalSkinShowcaseMain.tsx
  src/components/Others/CardSkin/CardSkinInventory.tsx
  src/services/notifications.service.ts
Labels: Adição/Feature, Code Review

#61 [ Gabriel Almeida ] Tweaks - Implementando parte de compra de uma skin em Detalhes da Skin (#272)
  src/components/Common/CommonSubtitle.tsx
  src/components/Icons/IconCheckPayment.tsx
  src/components/Icons/IconGift.tsx
  src/components/Icons/IconRecusePayment.tsx
  src/components/Modal/ModalBuy/ModalBuyMain.tsx
  src/components/Modal/ModalBuy/ModalBuySkin.tsx
  src/components/Modal/ModalBuy/ModalComfirm.tsx
  src/components/Modal/ModalBuy/ModalExchange.tsx
  src/components/Modal/ModalBuy/ModalInfoSkin.tsx
  src/components/Modal/ModalBuy/ModalPamentMade.tsx
  src/components/Modal/ModalBuy/ModalPaymentRefused.tsx
  src/components/Modal/ModalBuy/ModalTitleSkin.tsx
  src/components/Modal/ModalProcessing/index.tsx
  src/components/Modal/ModalSkinShowcase/ModalSkinShowcaseInfo.tsx
  src/components/Others/CardSkinModal/CardSkinModalContent.tsx
  src/components/Others/CardSkinModal/CardSkinModalRoot.tsx
  src/components/Others/CardSkinModal/index.tsx
  src/components/Pages/PageDetails/PageDetailsMain.tsx
  src/components/Pages/PageDetails/PageDetailsSkin.tsx
  src/components/Pages/PageHome/PageHomeSkins.tsx
  src/components/Pages/PageInventory/PageInventorySummary.tsx
  src/interfaces/ISkins.ts
  src/services/notifications.service.ts
  src/services/skin.service.ts
  src/stores/interfaces/skins.interface.ts
  src/stores/skins.store.ts
Labels: Adição/Feature, Code Review

#65 [ Gabriel Almeida ] Tweaks - Adicionar últimas vendas de um vendedor (#279)
  src/components/Modal/ModalSkinShowcase/ModalSkinShowcaseInfo.tsx
  src/components/Pages/PageDetails/PageDetailsMain.tsx
  src/components/Pages/PageDetails/PageDetailsVendas.tsx
  src/interfaces/user.interface.ts
  src/services/notifications.service.ts
  src/services/user.service.ts
Labels: Adição/Feature, Code Review

#63 [ Gabriel Almeida ] Tweaks - Limitando input de recarga para no máximo 25k e corrigindo posição do tipo de uma skin
  src/components/Modal/ModalPayment/add.schema.ts
  src/components/Others/OtherCard/OtherCard.tsx
Labels: Code Review

#72 [ Task - 43 ] Bugfix - NaN aparecendo no Modal de Anúncio
  src/components/Modal/ModalSkinShowcase/ModalSkinShowcaseInfo.tsx
  src/components/Pages/PageInventory/PageInventorySummary.tsx
Labels: Bug, Code Review

#73 [ Task - 22 & 48 ] Tweaks - Adiciona tendência de mercado do item && Altera o percentual do aluguel para 23%
  src/components/Modal/ModalSkinShowcase/ModalSkinShowcaseInfo.tsx
  src/components/Pages/PageDetails/PageDetailsMain.tsx
  src/components/Pages/PageDetails/PageDetailsSkin.tsx
  src/interfaces/ISkins.ts
Labels: Adição/Feature, Code Review

#77 [ Task - 50 ] Modal - Devolução de Item na Página de Perfil
  src/components/Modal/ModalEditionItem/ModalEditionItemMain.tsx
  src/components/Modal/ModalEditionItem/ModalInfoItem.tsx
  src/components/Modal/ModalEditionItem/ModalItemShow.tsx
  src/components/Others/CardSkin/CardSkinInventory.tsx
  src/components/Others/CartSkinCard/index.tsx
  src/components/Others/OtherCard/OtherCard.tsx
  src/components/Others/PersonProfile/index.tsx
  src/components/Others/Skins/AllSkins/index.tsx
  src/components/Others/SkinsSemelhantes/index.tsx
  src/components/Pages/PageDetails/PageDetailsPerfil.tsx
  src/components/Pages/PageDetails/PageDetailsSkin.tsx
  src/components/Pages/PageProfile/PageProfileSelf.tsx
  src/components/Pages/PageProfile/PageProfileUser.tsx
  src/components/Pages/PageStore/PageStoreSkins.tsx
  src/interfaces/ISkins.ts
  src/services/interfaces/user.interface.ts
Labels: Adição/Feature, Code Review

#78 [ Task - 57 ] Modal - Devolução de Item na Página de Perfil
  src/components/Icons/IconReturn.tsx
  src/components/Icons/IconShield.tsx
  src/components/Icons/payment/IconBankTransfer.tsx
  src/components/Icons/payment/IconMastercard.tsx
  src/components/Icons/payment/IconPayPal.tsx
  src/components/Modal/ModalBuy/ModalBuySkin.tsx
  src/components/Modal/ModalBuy/ModalInfoSkin.tsx
  src/components/Modal/ModalBuy/ModalTitleSkin.tsx
  src/components/Modal/ModalReturnSkin/ModalChoiceRetrievePayment.tsx
  src/components/Modal/ModalReturnSkin/ModalInfoRent.tsx
  src/components/Modal/ModalReturnSkin/ModalLeftToSteam.tsx
  src/components/Modal/ModalReturnSkin/ModalRefundMethod/CardPaymentMethod.tsx
  src/components/Modal/ModalReturnSkin/ModalRefundMethod/ModalReturnRefundMethod.tsx
  src/components/Modal/ModalReturnSkin/ModalReturnKYC.tsx
  src/components/Modal/ModalReturnSkin/ModalReturnMain.tsx
  src/components/Modal/ModalReturnSkin/ModalReturnSkin.tsx
  src/components/Others/OtherCard/OtherCard.tsx
  src/components/Pages/PageProfile/PageProfileSelf.tsx
  src/stores/interfaces/modal.interface.ts
  src/stores/modal.store.ts
Labels: Adição/Feature, Code Review

#79 Tweaks - Corrigir ícone da Home
  src/components/Icons/IconDevolution.tsx
  src/components/Icons/IconMagnifyingGlass.tsx
  src/components/Icons/IconPhone.tsx
  src/components/Icons/IconShield.tsx
  src/components/Icons/IconShieldGreen.tsx
  src/components/Modal/ModalPayment/ModalPaymentRetrieve/ModalPaymentRetrieveSelection.tsx
  src/components/Modal/ModalReturnSkin/ModalChoiceRetrievePayment.tsx
  src/components/Modal/ModalReturnSkin/ModalReturnKYC.tsx
  src/components/Others/KYCMessage/index.tsx
Labels: Code Review, Refatoração

#80 [Task - 69] Modal - Conexão do modal de edição de um item com o back
  src/components/Modal/ModalEditionItem/ModalEditionItemMain.tsx
  src/components/Modal/ModalEditionItem/ModalInfoItem.tsx
  src/services/skin.service.ts
Labels: Adição/Feature, Code Review
